apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-parameters-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: log-level
      value: INFO
    - name: log-leve2
      value: ERROR
  templates:
  - name: main
    steps:
    - - name: step-a
        template: a
      - name: step-b
        template: b

  - name: a
    container:
      image: nginx:latest
      env:
      - name: LOG_LEVEL
        value: "{{workflow.parameters.log-level}}"
      command: ["/bin/bash", "-c"]
      args: ["echo LOG_LEVEL is $LOG_LEVEL"]

  - name: b
    container:
      image: nginx:latest
      env:
      - name: LOG_LEVEL
        value: "{{workflow.parameters.log-leve2}}"
      command: ["/bin/bash", "-c"]
      args: ["echo Running B with LOG_LEVEL: $LOG_LEVEL"]
