apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
  namespace: argo
spec:
  entrypoint: artifact-example
  templates:
    - name: artifact-example
      steps:
        - - name: generate-artifact
            template: generate-artifact
        - - name: consume-artifact
            template: consume-artifact
            arguments:
              artifacts:
                - name: message
                  from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

    - name: generate-artifact
      outputs:
        artifacts:
          - name: hello-art
            path: /tmp/hello_world.txt
      container:
        image: alpine:3.7
        command: [sh, -c]
        args: ["echo hello world > /tmp/hello_world.txt"]

    - name: consume-artifact
      inputs:
        artifacts:
          - name: message
            path: /tmp/message
      container:
        image: alpine:3.7
        command: [sh, -c]
        args: ["cat /tmp/message"]
